import Head from "next/head";
import { speakersData } from "../data/speakers";
import dynamic from "next/dynamic";
import { process } from "@progress/kendo-data-query";
import { useState } from "react";
import "@progress/kendo-theme-default/dist/all.css";

const ViewerComponent = dynamic(() => import("../components/ViewerComponent"), {
  ssr: false,
});

export default function Home() {
  const [selected, setSelected] = useState('Multiselect'); // Initialize with a default report
  const [gridDataState, setGridDataState] = useState(() => ({
    data: process([], { sort: [{ field: "Name", dir: "asc" }] }), // Assuming initial data setup
  }));

  const handleChange = (event) => {
    setSelected(event.target.value);
  };

  return (
    <>
      <Head>
        <title>Telerik React App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div label="React Report Viewer">
          <ViewerComponent reportName={selected + ".trdp"} data={gridDataState.data}></ViewerComponent>
          <select value={selected} onChange={handleChange}>
            {/* <option value="SampleReport">SampleReport</option> */}
            <option value="chartsTrial">chartsTrial</option>
            <option value="RequisitionAnalysisReport">RequisitionAnalysisReport</option>
            <option value="SubReport">SubReport</option>
            {/* <option value="MoreColums">MoreColums</option> */}
            <option value="Multiselect">Multiselect</option>
          </select>
          <div>Selected: {selected}</div>
        </div>
      </div>
    </>
  );
}