import Head from "next/head";
import { speakersData } from "../data/speakers";
import dynamic from 'next/dynamic'
import { process } from '@progress/kendo-data-query';
import { useState } from "react";
import '@progress/kendo-theme-default/dist/all.css';

const ViewerComponent = dynamic(() => import('../components/ViewerComponent'), {
  ssr: false,
})


export default function Home() {

  const [gridDataState, setGridDataState] = useState(() => ({
    data: process(speakersData, {
      sort: [
        { field: "Name", dir: "asc" }
      ],
    }),

  })); 


    return (
      <>
      <Head>
          <title>Telerik Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div label="React Report Viewer">
          <div>
            <ViewerComponent data={gridDataState.data}></ViewerComponent>
          </div>
        </div>
      </div>
    </>
    );
}
